spring:
  cloud:
    stream:
      kafka:
        streams:
          binder:
            configuration:
              default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
          bindings.customInput.consumer.application-id: stream-joiner-test-app-id
          bindings.anotherCustomInput.consumer.application-id: another-stream-joiner-test-app-id
      bindings:
        customInput:
          destination: join-topic-1
        anotherCustomInput:
          destination: join-topic-2