spring:
  kafka:
    bootstrap-servers: blade1:9092
  cloud:
    stream:
      kafka:
        streams:
          binder.configuration:
            default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
            default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
          bindings.input.consumer.application-id: word-count-test-app-id
      bindings:
        input:
          group: wordsInputGroup
          destination: wordsTopic
        output:
          destination: streamOutput
        input1:
          group: wordsTestInputGroup
          destination: wordsTopic
        output1:
          destination: wordsTopic
spring.cloud.stream.bindings.input1.binder: kafka
spring.cloud.stream.bindings.output1.binder: kafka